# auto generated by "smithed_librairies/packs/crafter.py" at build time
# a list of tools, with their max_damage like this : 
# execute 
    # if data entity @s {HandItems:[{id:"minecraft:wooden_sword"}]} 
    # if score $temp1 smithed.data matches 59.. 
    # run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:bow"}]} if score $temp1 smithed.data matches 384.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:brush"}]} if score $temp1 smithed.data matches 64.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:carrot_on_a_stick"}]} if score $temp1 smithed.data matches 25.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:chainmail_boots"}]} if score $temp1 smithed.data matches 195.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:chainmail_chestplate"}]} if score $temp1 smithed.data matches 240.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:chainmail_helmet"}]} if score $temp1 smithed.data matches 165.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:chainmail_leggings"}]} if score $temp1 smithed.data matches 225.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:crossbow"}]} if score $temp1 smithed.data matches 465.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_axe"}]} if score $temp1 smithed.data matches 1561.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_boots"}]} if score $temp1 smithed.data matches 429.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_chestplate"}]} if score $temp1 smithed.data matches 528.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_helmet"}]} if score $temp1 smithed.data matches 363.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_hoe"}]} if score $temp1 smithed.data matches 1561.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_leggings"}]} if score $temp1 smithed.data matches 495.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_pickaxe"}]} if score $temp1 smithed.data matches 1561.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_shovel"}]} if score $temp1 smithed.data matches 1561.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:diamond_sword"}]} if score $temp1 smithed.data matches 1561.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:elytra"}]} if score $temp1 smithed.data matches 432.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:fishing_rod"}]} if score $temp1 smithed.data matches 64.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:flint_and_steel"}]} if score $temp1 smithed.data matches 64.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_axe"}]} if score $temp1 smithed.data matches 32.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_boots"}]} if score $temp1 smithed.data matches 91.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_chestplate"}]} if score $temp1 smithed.data matches 112.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_helmet"}]} if score $temp1 smithed.data matches 77.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_hoe"}]} if score $temp1 smithed.data matches 32.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_leggings"}]} if score $temp1 smithed.data matches 105.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_pickaxe"}]} if score $temp1 smithed.data matches 32.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_shovel"}]} if score $temp1 smithed.data matches 32.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:golden_sword"}]} if score $temp1 smithed.data matches 32.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_axe"}]} if score $temp1 smithed.data matches 250.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_boots"}]} if score $temp1 smithed.data matches 195.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_chestplate"}]} if score $temp1 smithed.data matches 240.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_helmet"}]} if score $temp1 smithed.data matches 165.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_hoe"}]} if score $temp1 smithed.data matches 250.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_leggings"}]} if score $temp1 smithed.data matches 225.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_pickaxe"}]} if score $temp1 smithed.data matches 250.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_shovel"}]} if score $temp1 smithed.data matches 250.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:iron_sword"}]} if score $temp1 smithed.data matches 250.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:leather_boots"}]} if score $temp1 smithed.data matches 65.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:leather_chestplate"}]} if score $temp1 smithed.data matches 80.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:leather_helmet"}]} if score $temp1 smithed.data matches 55.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:leather_leggings"}]} if score $temp1 smithed.data matches 75.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:mace"}]} if score $temp1 smithed.data matches 250.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_axe"}]} if score $temp1 smithed.data matches 2031.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_boots"}]} if score $temp1 smithed.data matches 481.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_chestplate"}]} if score $temp1 smithed.data matches 592.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_helmet"}]} if score $temp1 smithed.data matches 407.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_hoe"}]} if score $temp1 smithed.data matches 2031.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_leggings"}]} if score $temp1 smithed.data matches 555.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_pickaxe"}]} if score $temp1 smithed.data matches 2031.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_shovel"}]} if score $temp1 smithed.data matches 2031.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:netherite_sword"}]} if score $temp1 smithed.data matches 2031.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:shears"}]} if score $temp1 smithed.data matches 238.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:shield"}]} if score $temp1 smithed.data matches 336.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:stone_axe"}]} if score $temp1 smithed.data matches 131.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:stone_hoe"}]} if score $temp1 smithed.data matches 131.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:stone_pickaxe"}]} if score $temp1 smithed.data matches 131.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:stone_shovel"}]} if score $temp1 smithed.data matches 131.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:stone_sword"}]} if score $temp1 smithed.data matches 131.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:trident"}]} if score $temp1 smithed.data matches 250.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:turtle_helmet"}]} if score $temp1 smithed.data matches 275.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:warped_fungus_on_a_stick"}]} if score $temp1 smithed.data matches 100.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:wolf_armor"}]} if score $temp1 smithed.data matches 64.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:wooden_axe"}]} if score $temp1 smithed.data matches 59.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:wooden_hoe"}]} if score $temp1 smithed.data matches 59.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:wooden_pickaxe"}]} if score $temp1 smithed.data matches 59.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:wooden_shovel"}]} if score $temp1 smithed.data matches 59.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub
execute if data entity @s {HandItems: [{id: "minecraft:wooden_sword"}]} if score $temp1 smithed.data matches 59.. run function smithed.crafter:v0.4.0/block/table/crafting/output/clear_input/delete_tool/sub

